spring.application.name=aimda

# ==========================================
# SERVER
# ==========================================
server.port=${SERVER_PORT}

# ==========================================
# POSTGRESQL DATABASE CONNECTION PROPERTIES
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA & HIBERNATE CORE CONFIGURATIONS
# ==========================================
# Spring Boot automatically detects the Dialect, but you can declare it explicitly:
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Controls how Hibernate initializes the database schema automatically
# Choices: none, validate, update, create, create-drop
spring.jpa.hibernate.ddl-auto=update


# ==========================================
# DEBUGGING & LOGGING
# ==========================================
# Print SQL queries to the console log
spring.jpa.show-sql=true

# Format the printed SQL to make it easier to read
spring.jpa.properties.hibernate.format_sql=true
